### ISSUE TITLE
FastRhino R68S固件OpenClash问题

### ISSUE THREAD

**Issue by Sankyu-3399** [kiddin9/Kwrt#1579]
我的设备时FastRhino R68S
固件信息
分支: 23.05.0
内核: 5.15.133
生成日期:	2023-11-06 18:54:08
这个固件使用OpenClash时
2023-11-06 20:00:33 警告：OpenClash 启动成功，检测到您启用了IPv6的DHCP服务，可能会造成连接异常！
2023-11-06 20:00:33 第九步: 添加计划任务,启动进程守护程序...
2023-11-06 20:00:32 第八步: 重启 Dnsmasq 程序...
到这一步也就是启动进程守护程序后Mate内核会启动成功但是马上崩溃,TUN内核也是一样
以下是我的内核日志
github.com/Dreamacro/clash/hub/executor/executor.go:290 +0x78
created by github.com/Dreamacro/clash/hub/executor.loadRuleProvider
	github.com/Dreamacro/clash/hub/executor/executor.go:292 +0x74
github.com/Dreamacro/clash/hub/executor.loadRuleProvider.func1()
	github.com/Dreamacro/clash/hub/executor/executor.go:268 +0xd0
github.com/Dreamacro/clash/hub/executor.loadProvider({0xffff5af3b1d0, 0x400000e348})
	github.com/Dreamacro/clash/rules/provider/provider.go:67 +0x30
github.com/Dreamacro/clash/rules/provider.(*ruleSetProvider).Initial(0x400003d3e0)
	github.com/Dreamacro/clash/component/resource/fetcher.go:83 +0x2d0
github.com/Dreamacro/clash/component/resource.(*Fetcher[...]).Initial(0x10e0240)
	github.com/Dreamacro/clash/rules/provider/provider.go:132 +0x5c
github.com/Dreamacro/clash/rules/provider.NewRuleSetProvider.func2({0x4000348000, 0x33dff, 0x36000})
	github.com/Dreamacro/clash/rules/provider/provider.go:243 +0x4dc
github.com/Dreamacro/clash/rules/provider.rulesParse({0x4000348000, 0x33dff, 0x36000}, {0x10d94b0, 0x4006310108}, 0x0)
	github.com/Dreamacro/clash/rules/provider/ipcidr_strategy.go:38 +0x30
github.com/Dreamacro/clash/rules/provider.(*ipcidrStrategy).Insert(0x4006310108, {0x400971ff38, 0x17})
	github.com/Dreamacro/clash/component/trie/ipcidr_trie.go:46 +0x50
github.com/Dreamacro/clash/component/trie.(*IpCidrTrie).AddIpCidrForString(0x0?, {0x400971ff38?, 0xa45690?})
	github.com/Dreamacro/clash/component/trie/ipcidr_trie.go:34 +0x84
github.com/Dreamacro/clash/component/trie.(*IpCidrTrie).AddIpCidr(0x400971ff38?, 0x17?)
	github.com/Dreamacro/clash/component/trie/ipcidr_trie.go:123 +0x34
github.com/Dreamacro/clash/component/trie.addIpCidr(0x10?, 0x3?, {0x40068cd26c?, 0x10?, 0x10?}, 0x13?)
	github.com/Dreamacro/clash/component/trie/ipcidr_trie.go:146 +0x4f8
github.com/Dreamacro/clash/component/trie.addIpv4Cidr(0x4?, {0x40068cd26c, 0x4, 0x13?}, 0x10)
goroutine 868 [running]:
panic: runtime error: index out of range [4] with length 4

**Comment by Sankyu-3399** [comment]
无法执行 opkg update 命令：SyntaxError: Unexpected end of JSON input
这是我更新软件包,软件列表时的错误,固件是全新安装的,除了配置PPPOE后无任何修改
